flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:raymoo/NEET
    commit: c86fc78c8c9df6c1dccff5a58403b833bac636eb
extra-deps:
- optparse-generic-1.1.0
resolver: lts-5.12
